apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-service
  namespace: kube-public
spec:
  selector:
    k8s-app: traefik
  ports:
  - port: 80
    name: httpproxy
  - port: 8080
    name: admindashboard
  type: NodePort